In [1]:
import pdb_numpy
import pdb_numpy.alignement

In [2]:
ref = pdb_numpy.Coor(pdb_id="7XZZ")
ref_2 = pdb_numpy.Coor(pdb_id="7EEU")

In [3]:
seq_1 = ref.get_aa_seq()
seq_1

{'A': 'PHRYRPGTVALREIRRYQKSTELLIRKLPFQRLVREIAQDFKTDLRFQSSAVMALQEACEAYLVGLFEDTNLCAIHAKRVTIMPKDIQLARRIRGER',
 'B': 'VLRDNIQGITKPAIRRLARRGGVKRISGLIYEETRGVLKVFLENVIRDAVTYTEHAKRKTVTAMDVVYALKRQGRTLYGFGG',
 'C': 'RAKAKTRSSRAGLQFPVGRVHRLLRKGNYSERVGAGAPVYLAAVLEYLTAEILELAGNAARDNKKTRIIPRHLQLAIRNDEELNKLLGRVTIAQGGVLPNIQAVLLPKK',
 'D': 'KRSRKESYSIYVYKVLKQVHPDTGISSKAMGIMNSFVNDIFERIAGEASRLAHYNKRSTITSREIQTAVRLLLPGELAKHAVSEGTKAVTKYTSA',
 'E': 'KPHRYRPGTVALREIRRYQKSTELLIRKLPFQRLVREIAQDFKTDLRFQSSAVMALQEACEAYLVGLFEDTNLCAIHAKRVTIMPKDIQLARRIRGER',
 'F': 'RDNIQGITKPAIRRLARRGGVKRISGLIYEETRGVLKVFLENVIRDAVTYTEHAKRKTVTAMDVVYALKRQGRTLYGFGG',
 'G': 'KAKTRSSRAGLQFPVGRVHRLLRKGNYSERVGAGAPVYLAAVLEYLTAEILELAGNAARDNKKTRIIPRHLQLAIRNDEELNKLLGRVTIAQGGVLPNIQAVLLPK',
 'H': 'RSRKESYSIYVYKVLKQVHPDTGISSKAMGIMNSFVNDIFERIAGEASRLAHYNKRSTITSREIQTAVRLLLPGELAKHAVSEGTKAVTKYTSAK',
 'K': 'SSSVPSQKTYQGSYGFRLGFLHSGTAKSVTCTYSPALNKMFCQLAKTCPVQLWVDSTPPPGTRVRAMAIYKQSQHMTEVVRRCPHHERCSDSDGLAPPQHLIRVEGNLRVEYLDDRNTFRHSVVVPYEPPEVGSDCTTIHYNYMCNSSCMG

In [4]:
seq_2 = ref_2.get_aa_seq()
seq_2

{'A': 'SSVPSQKTYQGSYGFRLGFLHSGTAKSVTCTYSPALNKMFCQLAKTCPVQLWVDSTPPPGTRVRAMAIYKQSQHMTEVVRRCPHHERCSDSDGLAPPQHLIRVEGNLRVEYLDDRNTFRHSVVVPYEPPEVGSDCTTIHYNYMCNSSCMGGMNRRPILTIITLEDSSGNLLGRNSFEVRVCACPGRDWRTEEENLRKK',
 'B': 'SSVPSQKTYQGSYGFRLGFLHSGTAKSVTCTYSPALNKMFCQLAKTCPVQLWVDSTPPPGTRVRAMAIYKQSQHMTEVVRRCPHHERCSDSDGLAPPQHLIRVEGNLRVEYLDDRNTFRHSVVVPYEPPEVGSDCTTIHYNYMCNSSCMGGMNRRPILTIITLEDSSGNLLGRNSFEVRVCACPGRDWRTEEENLRKK',
 'C': 'SSVPSQKTYQGSYGFRLGFLHSGTAKSVTCTYSPALNKMFCQLAKTCPVQLWVDSTPPPGTRVRAMAIYKQSQHMTEVVRRCPHHERCSDSDGLAPPQHLIRVEGNLRVEYLDDRNTFRHSVVVPYEPPEVGSDCTTIHYNYMCNSSCMGGMNRRPILTIITLEDSSGNLLGRNSFEVRVCACPGRDWRTEEENLRKK',
 'D': 'SSVPSQKTYQGSYGFRLGFLHSGTAKSVTCTYSPALNKMFCQLAKTCPVQLWVDSTPPPGTRVRAMAIYKQSQHMTEVVRRCPHHERCSDSDGLAPPQHLIRVEGNLRVEYLDDRNTFRHSVVVPYEPPEVGSDCTTIHYNYMCNSSCMGGMNRRPILTIITLEDSSGNLLGRNSFEVRVCACPGRDWRTEEENLRKK',
 'E': 'SSVPSQKTYQGSYGFRLGFLHSGTAKSVTCTYSPALNKMFCQLAKTCPVQLWVDSTPPPGTRVRAMAIYKQSQHMTEVVRRCPHHERCSDSDGLAPPQHLIRVEGNLRVEYLDDRNTFRHSVVVPYEPPEVGSDCTTIHYNYMCNSSCMGGMNRRPILTII

## Test performance

In [5]:
pdb_numpy.alignement.align_seq_cython_2(seq_1["K"], seq_2["A"])

('SSSVPSQKTYQGSYGFRLGFLHSGTAKSVTCTYSPALNKMFCQLAKTCPVQLWVDSTPPPGTRVRAMAIYKQSQHMTEVVRRCPHHERCSDSDGLAPPQHLIRVEGNLRVEYLDDRNTFRHSVVVPYEPPEVGSDCTTIHYNYMCNSSCMGGMNRRPILTIITLEDSSGNLLGRNSFEVRVCACPGRD-RRTEEENLR-K',
 '-SSVPSQKTYQGSYGFRLGFLHSGTAKSVTCTYSPALNKMFCQLAKTCPVQLWVDSTPPPGTRVRAMAIYKQSQHMTEVVRRCPHHERCSDSDGLAPPQHLIRVEGNLRVEYLDDRNTFRHSVVVPYEPPEVGSDCTTIHYNYMCNSSCMGGMNRRPILTIITLEDSSGNLLGRNSFEVRVCACPGRDW-RTEEENLRKK')

In [6]:
import cProfile
cProfile.run('pdb_numpy.alignement.align_seq_cython_2(seq_1["K"], seq_2["A"])', sort='time')

         408 function calls in 0.002 seconds

   Ordered by: internal time

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
        1    0.001    0.001    0.001    0.001 align_cython.pyx:259(align_seq_2)
        2    0.000    0.000    0.000    0.000 align_cython.pyx:239(convert_seq)
      396    0.000    0.000    0.000    0.000 align_cython.pyx:193(convert_aa)
        1    0.000    0.000    0.000    0.000 align_cython.pyx:17(get_blosum62)
        1    0.000    0.000    0.002    0.002 {built-in method builtins.exec}
        1    0.000    0.000    0.001    0.001 __init__.py:109(align_seq_cython_2)
        1    0.000    0.000    0.000    0.000 <frozen importlib._bootstrap>:1053(_handle_fromlist)
        1    0.000    0.000    0.001    0.001 <string>:1(<module>)
        1    0.000    0.000    0.000    0.000 <frozen importlib._bootstrap>:404(parent)
        1    0.000    0.000    0.000    0.000 {built-in method builtins.hasattr}
        1    0.000    0.000    0.000  

In [7]:
%timeit pdb_numpy.alignement.align_seq_cython_2(seq_1["K"], seq_2["A"])

379 µs ± 18.2 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [8]:
%timeit pdb_numpy.alignement.align_seq_cython(seq_1["K"], seq_2["A"])

5.38 ms ± 13.5 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [9]:
pdb_numpy.alignement.align_seq_cython(seq_1["K"], seq_2["A"])

('SSSVPSQKTYQGSYGFRLGFLHSGTAKSVTCTYSPALNKMFCQLAKTCPVQLWVDSTPPPGTRVRAMAIYKQSQHMTEVVRRCPHHERCSDSDGLAPPQHLIRVEGNLRVEYLDDRNTFRHSVVVPYEPPEVGSDCTTIHYNYMCNSSCMGGMNRRPILTIITLEDSSGNLLGRNSFEVRVCACPGRD-RRTEEENLR-K',
 '-SSVPSQKTYQGSYGFRLGFLHSGTAKSVTCTYSPALNKMFCQLAKTCPVQLWVDSTPPPGTRVRAMAIYKQSQHMTEVVRRCPHHERCSDSDGLAPPQHLIRVEGNLRVEYLDDRNTFRHSVVVPYEPPEVGSDCTTIHYNYMCNSSCMGGMNRRPILTIITLEDSSGNLLGRNSFEVRVCACPGRDW-RTEEENLRKK')

In [10]:
pdb_numpy.alignement.align_seq_cython_2(seq_1["K"], seq_2["A"])

('SSSVPSQKTYQGSYGFRLGFLHSGTAKSVTCTYSPALNKMFCQLAKTCPVQLWVDSTPPPGTRVRAMAIYKQSQHMTEVVRRCPHHERCSDSDGLAPPQHLIRVEGNLRVEYLDDRNTFRHSVVVPYEPPEVGSDCTTIHYNYMCNSSCMGGMNRRPILTIITLEDSSGNLLGRNSFEVRVCACPGRD-RRTEEENLR-K',
 '-SSVPSQKTYQGSYGFRLGFLHSGTAKSVTCTYSPALNKMFCQLAKTCPVQLWVDSTPPPGTRVRAMAIYKQSQHMTEVVRRCPHHERCSDSDGLAPPQHLIRVEGNLRVEYLDDRNTFRHSVVVPYEPPEVGSDCTTIHYNYMCNSSCMGGMNRRPILTIITLEDSSGNLLGRNSFEVRVCACPGRDW-RTEEENLRKK')

In [11]:
pdb_numpy.alignement.align_seq_C(seq_1["K"], seq_2["A"])

('SSSVPSQKTYQGSYGFRLGFLHSGTAKSVTCTYSPALNKMFCQLAKTCPVQLWVDSTPPPGTRVRAMAIYKQSQHMTEVVRRCPHHERCSDSDGLAPPQHLIRVEGNLRVEYLDDRNTFRHSVVVPYEPPEVGSDCTTIHYNYMCNSSCMGGMNRRPILTIITLEDSSGNLLGRNSFEVRVCACPGRD-RRTEEENLR-K',
 '-SSVPSQKTYQGSYGFRLGFLHSGTAKSVTCTYSPALNKMFCQLAKTCPVQLWVDSTPPPGTRVRAMAIYKQSQHMTEVVRRCPHHERCSDSDGLAPPQHLIRVEGNLRVEYLDDRNTFRHSVVVPYEPPEVGSDCTTIHYNYMCNSSCMGGMNRRPILTIITLEDSSGNLLGRNSFEVRVCACPGRDW-RTEEENLRKK')

In [12]:
%timeit pdb_numpy.alignement.align_seq(seq_1["K"], seq_2["A"])

118 ms ± 327 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [13]:
%timeit pdb_numpy.alignement.align_seq_C(seq_1["K"], seq_2["A"])

535 µs ± 2.26 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [14]:
%load_ext line_profiler

In [15]:
%lprun -f pdb_numpy.alignement.align_seq_C pdb_numpy.alignement.align_seq_C(seq_1["K"], seq_2["A"])

Timer unit: 1e-09 s

Total time: 0.00155912 s
File: /home/murail/miniforge3/envs/docking/lib/python3.10/site-packages/pdb_numpy/alignement/__init__.py
Function: align_seq_C at line 16

Line #      Hits         Time  Per Hit   % Time  Line Contents
    16                                           def align_seq_C(seq_1, seq_2, gap_cost=-11, gap_extension=-1):
    17                                               """Align two amino acid sequences using the Waterman - Smith Algorithm.
    18                                           
    19                                               Parameters
    20                                               ----------
    21                                               seq_1 : str
    22                                                   First sequence to align
    23                                               seq_2 : str
    24                                                   Second sequence to align
    25                                      

## Test memory leak

- launch `htop` or `top` in a terminal to monitor memory usage 

In [16]:
for i in range(100000):
    pdb_numpy.alignement.align_seq_C(seq_1["K"], seq_2["A"])
    if i % 10000 == 0:
        print(i)

0


10000
20000


KeyboardInterrupt: 

In [ ]:
%load_ext Cython

In [ ]:
%%cython -a

import numpy as np
cimport numpy as np

from libc.string cimport strcpy, strlen


cdef int convert_aa(char aa):

    if aa == b'A':
        return 0
    if aa == b'R':
        return 1
    if aa == b'N':
        return 2
    if aa == b'D':
        return 3
    if aa == b'C':
        return 4
    if aa == b'Q':
        return 5
    if aa == b'E':
        return 6
    if aa == b'G':
        return 7
    if aa == b'H':
        return 8
    if aa == b'I':
        return 9
    if aa == b'L':
        return 10
    if aa == b'K':
        return 11
    if aa == b'M':
        return 12
    if aa == b'F':
        return 13
    if aa == b'P':
        return 14
    if aa == b'S':
        return 15
    if aa == b'T':
        return 16
    if aa == b'W':
        return 17
    if aa == b'Y':
        return 18
    if aa == b'V':
        return 19

    return -1;

cdef np.ndarray[np.int8_t, ndim=1] convert_seq(char* seq):

    cdef unsigned int i, seq_len = 0;
    
    for i in range(strlen(seq)):
        if seq[i] != b'-':
            seq_len += 1
    
    cdef np.ndarray[np.int8_t, ndim=1] new_seq = np.empty((seq_len), dtype=np.int8)

    cdef int k = 0

    for i in range(strlen(seq)):
        if seq[i] != b'-':
            new_seq[k] = convert_aa(seq[i])
            k += 1

    return new_seq
    #print("new seq:", new_seq)
    
    
cdef np.ndarray[np.int8_t, ndim=2] get_blosum62():

    #     A  R  N  D  C  Q  E  G  H  I  L  K  M  F  P  S  T  W  Y  V  B  Z  X  *
    BLOSUM62_list = [
        [ 4, -1, -2, -2,  0, -1, -1,  0, -2, -1, -1, -1, -1, -2, -1,  1,  0, -3, -2,  0, -2, -1,  0, -4], # A
        [-1,  5,  0, -2, -3,  1,  0, -2,  0, -3, -2,  2, -1, -3, -2, -1, -1, -3, -2, -3, -1,  0, -1, -4], # R 
        [-2,  0,  6,  1, -3,  0,  0,  0,  1, -3, -3,  0, -2, -3, -2,  1,  0, -4, -2, -3,  3,  0, -1, -4], # N 
        [-2, -2,  1,  6, -3,  0,  2, -1, -1, -3, -4, -1, -3, -3, -1,  0, -1, -4, -3, -3,  4,  1, -1, -4], # D 
        [ 0, -3, -3, -3,  9, -3, -4, -3, -3, -1, -1, -3, -1, -2, -3, -1, -1, -2, -2, -1, -3, -3, -2, -4], # C 
        [-1,  1,  0,  0, -3,  5,  2, -2,  0, -3, -2,  1,  0, -3, -1,  0, -1, -2, -1, -2,  0,  3, -1, -4], # Q 
        [-1,  0,  0,  2, -4,  2,  5, -2,  0, -3, -3,  1, -2, -3, -1,  0, -1, -3, -2, -2,  1,  4, -1, -4], # E 
        [ 0, -2,  0, -1, -3, -2, -2,  6, -2, -4, -4, -2, -3, -3, -2,  0, -2, -2, -3, -3, -1, -2, -1, -4], # G 
        [-2,  0,  1, -1, -3,  0,  0, -2,  8, -3, -3, -1, -2, -1, -2, -1, -2, -2,  2, -3,  0,  0, -1, -4], # H 
        [-1, -3, -3, -3, -1, -3, -3, -4, -3,  4,  2, -3,  1,  0, -3, -2, -1, -3, -1,  3, -3, -3, -1, -4], # I 
        [-1, -2, -3, -4, -1, -2, -3, -4, -3,  2,  4, -2,  2,  0, -3, -2, -1, -2, -1,  1, -4, -3, -1, -4], # L 
        [-1,  2,  0, -1, -3,  1,  1, -2, -1, -3, -2,  5, -1, -3, -1,  0, -1, -3, -2, -2,  0,  1, -1, -4], # K 
        [-1, -1, -2, -3, -1,  0, -2, -3, -2,  1,  2, -1,  5,  0, -2, -1, -1, -1, -1,  1, -3, -1, -1, -4], # M 
        [-2, -3, -3, -3, -2, -3, -3, -3, -1,  0,  0, -3,  0,  6, -4, -2, -2,  1,  3, -1, -3, -3, -1, -4], # F 
        [-1, -2, -2, -1, -3, -1, -1, -2, -2, -3, -3, -1, -2, -4,  7, -1, -1, -4, -3, -2, -2, -1, -2, -4], # P 
        [ 1, -1,  1,  0, -1,  0,  0,  0, -1, -2, -2,  0, -1, -2, -1,  4,  1, -3, -2, -2,  0,  0,  0, -4], # S 
        [ 0, -1,  0, -1, -1, -1, -1, -2, -2, -1, -1, -1, -1, -2, -1,  1,  5, -2, -2,  0, -1, -1,  0, -4], # T 
        [-3, -3, -4, -4, -2, -2, -3, -2, -2, -3, -2, -3, -1,  1, -4, -3, -2, 11,  2, -3, -4, -3, -2, -4], # W 
        [-2, -2, -2, -3, -2, -1, -2, -3,  2, -1, -1, -2, -1,  3, -3, -2, -2,  2,  7, -1, -3, -2, -1, -4], # Y 
        [ 0, -3, -3, -3, -1, -2, -2, -3, -3,  3,  1, -2,  1, -1, -2, -2,  0, -3, -1,  4, -3, -2, -1, -4], # V 
        [-2, -1,  3,  4, -3,  0,  1, -1,  0, -3, -4,  0, -3, -3, -2,  0, -1, -4, -3, -3,  4,  1, -1, -4], # B 
        [-1,  0,  0,  1, -3,  3,  4, -2,  0, -3, -3,  1, -1, -3, -1,  0, -1, -3, -2, -2,  1,  4, -1, -4], # Z 
        [ 0, -1, -1, -1, -2, -1, -1, -1, -1, -1, -1, -1, -1, -1, -2,  0,  0, -2, -1, -1, -1, -1, -1, -4], # X 
        [-4, -4, -4, -4, -4, -4, -4, -4, -4, -4, -4, -4, -4, -4, -4, -4, -4, -4, -4, -4, -4, -4, -4,  1], # * 
    ]

    cdef np.ndarray[np.int8_t, ndim=2] BLOSUM62_array = np.array(BLOSUM62_list, dtype=np.int8)

    return BLOSUM62_array

def align_seq_2(char* seq_1, char* seq_2, short int gap_cost=-11, short int gap_extension=-1):
    """Align two amino acid sequences using the Waterman - Smith Algorithm.

    Parameters
    ----------
    seq_1 : str
        First sequence to align
    seq_2 : str
        Second sequence to align
    gap_cost : int, optional
        Cost of gap, by default -8
    gap_extension : int, optional
        Cost of gap extension, by default -2

    Returns
    -------
    str
        Aligned sequence 1
    str
        Aligned sequence 2
    """

    cdef:
        np.ndarray[np.int8_t, ndim=1] seq_1_int, seq_2_int
        int len_1, len_2, i, j, max_index
    
    seq_1_int = convert_seq(seq_1)
    seq_2_int = convert_seq(seq_2)

    len_1 = len(seq_1_int)
    len_2 = len(seq_2_int)


    # Initialize the matrix
    cdef:
        np.ndarray[np.int32_t, ndim=2] matrix = np.zeros((len_1 + 1, len_2 + 1), dtype=np.int32)
        np.ndarray[np.npy_bool, ndim=1] prev_line = np.zeros((len_2 + 1), dtype=np.bool_)
        int choices[3]
        bint prev
        np.ndarray[np.int8_t, ndim=2] BLOSUM_62_array = get_blosum62()

    choices[:] = [0,0,0]

    # Fill the matrix
    for i in range(1, len_1 + 1):
        prev = False  # insertion matrix[i, j - 1]
        for j in range(1, len_2 + 1):
            # Identify the BLOSUM62 score
            # Match
            choices[0] = matrix[i - 1, j - 1] + BLOSUM_62_array[seq_2_int[j - 1], seq_1_int[i - 1]]
            # Delete
            choices[1] = matrix[i - 1, j] + (gap_extension if prev else gap_cost)
            # Insert
            choices[2] = matrix[i, j - 1] + (
                gap_extension if prev_line[j] else gap_cost
            )

            max_index = np.argmax(choices)
            matrix[i, j] = choices[max_index]
            prev_line[j] = False
            prev = False

            if max_index == 1:
                prev = True
            elif max_index == 2:
                prev_line[j] = True


cdef char * ma_seq = "YO-YO"
cdef int * seq_int
res = convert_seq(ma_seq)
print(res)

blosum_matrix = get_blosum62()
print(blosum_matrix)


[18 -1 18 -1]
[[ 4 -1 -2 -2  0 -1 -1  0 -2 -1 -1 -1 -1 -2 -1  1  0 -3 -2  0 -2 -1  0 -4]
 [-1  5  0 -2 -3  1  0 -2  0 -3 -2  2 -1 -3 -2 -1 -1 -3 -2 -3 -1  0 -1 -4]
 [-2  0  6  1 -3  0  0  0  1 -3 -3  0 -2 -3 -2  1  0 -4 -2 -3  3  0 -1 -4]
 [-2 -2  1  6 -3  0  2 -1 -1 -3 -4 -1 -3 -3 -1  0 -1 -4 -3 -3  4  1 -1 -4]
 [ 0 -3 -3 -3  9 -3 -4 -3 -3 -1 -1 -3 -1 -2 -3 -1 -1 -2 -2 -1 -3 -3 -2 -4]
 [-1  1  0  0 -3  5  2 -2  0 -3 -2  1  0 -3 -1  0 -1 -2 -1 -2  0  3 -1 -4]
 [-1  0  0  2 -4  2  5 -2  0 -3 -3  1 -2 -3 -1  0 -1 -3 -2 -2  1  4 -1 -4]
 [ 0 -2  0 -1 -3 -2 -2  6 -2 -4 -4 -2 -3 -3 -2  0 -2 -2 -3 -3 -1 -2 -1 -4]
 [-2  0  1 -1 -3  0  0 -2  8 -3 -3 -1 -2 -1 -2 -1 -2 -2  2 -3  0  0 -1 -4]
 [-1 -3 -3 -3 -1 -3 -3 -4 -3  4  2 -3  1  0 -3 -2 -1 -3 -1  3 -3 -3 -1 -4]
 [-1 -2 -3 -4 -1 -2 -3 -4 -3  2  4 -2  2  0 -3 -2 -1 -2 -1  1 -4 -3 -1 -4]
 [-1  2  0 -1 -3  1  1 -2 -1 -3 -2  5 -1 -3 -1  0 -1 -3 -2 -2  0  1 -1 -4]
 [-1 -1 -2 -3 -1  0 -2 -3 -2  1  2 -1  5  0 -2 -1 -1 -1 -1  1 -3 -1 -1 -4]
 [-2 -3 -3 